services:
  grafana:
    image: grafana/grafana-enterprise
    ports:
      - 3000:3000

  agent:
    image: grafana/agent
    environment:
      AGENT_MODE: flow
    volumes:
      - ./grafana-agent:/etc/agent
    ports:
      - 12345:12345
      - 9125:9125/udp
    command: [run, --server.http.listen-addr=0.0.0.0:12345, /etc/agent/config.river]

  mimir:
    image: grafana/mimir
    volumes:
      - ./mimir:/etc/mimir
    ports:
      - 9090:9090
    command: --config.file=/etc/mimir/demo.yaml

  tempo:
    image: grafana/tempo
    volumes:
      - ./tempo/tempo.yaml:/etc/tempo.yaml
      - ./tempo/data:/tmp/tempo
    command: [ "-config.file=/etc/tempo.yaml" ]
    ports:
      - 3200:3200
      - 4318:4318
